# Generated by Django 2.2.16 on 2020-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('children', models.ManyToManyField(blank=True, related_name='parents', to='products.Category', verbose_name='Дочерняя категория')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='products_images', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('category', models.ManyToManyField(related_name='products', to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
